### ISSUE TITLE
Kaby Lake microprocessor

### ISSUE THREAD

**Issue by JaspinderKaur07** [IAIK/flush_flush#11]
Has anyone know the cache slice reverse engineeering function for KabyLake microprocessor or how to get it?

**Comment by dgruss** [comment]
There are published papers on how to reverse-engineer it.

**Comment by JaspinderKaur07** [comment]
I have tried all these but it still did not work. Sir, any idea what other reason it could be

**Comment by dgruss** [comment]
No... they should work...
