### ISSUE TITLE
Has anyone successfully performed the Prime+Probe attack ?

### ISSUE THREAD

**Issue by combinedwu** [IAIK/flush_flush#15]
I can't build the useful eviction set for Prime+Prome attack, since my intel version is i7-11800H equipped with Tiger Lake-H architecture. Can someone share your cpu version which can successfully perform this attack ?

**Comment by dgruss** [comment]
Your CPU is too new. Try an i7-6700K.

**Comment by combinedwu** [comment]
Thank for your reply. I have tried the i7-6700k, but it's still not work. 
I also tried the same method on i5-2520m with published reverse-engineering hash function, and it successfully worked.
Also the PROBE_COUNT parameter is inconsistent in aes/pp/spy.cpp and it's corresponding histogram/pp/calibration.c.
I can't figure out it.
Great thanks to your team. It already helped me a lot for my graduate paper. Thank you very, very much.
![i7_6700k](https://github.com/IAIK/flush_flush/assets/80262489/481f0c28-0416-4e69-b4ed-472ba0d83c8f)

**Comment by combinedwu** [comment]
I have also tested the eviction set built by the PP code on i7-6700k. It shows the eviction set has effect. When I filled the eviction set and then access target address again, it does causes difference with about 30 cycles high. A bit weird number. Hope other learner can share your experiment result.

**Comment by dgruss** [comment]
30 is not enough... should be several hundred cycles... probably needs 
some fine-tuning of the parameters... eviction set size, maybe also the 
access pattern...

**Comment by combinedwu** [comment]
Thanks. I have tried another cpu version i7-4770 with Haswell architecture to recover AES key. It turns out the code works very well on this Haswell. I guess the SkyLake architecture may be more sophisticated and I need to study deeper in the future. I also read quite a lot of papers published by your team, very valuable. Just to express my sincere respect!
