### ISSUE TITLE
Compilation error: error: inconsistent operand constraints in an ‘asm’

### ISSUE THREAD

**Issue by Redent0r** [IAIK/flush_flush#2]
Hello, I am getting this when I try to compile the flush flush calibration utility:
`error: inconsistent operand constraints in an ‘asm’` on a VM. (I can compile it on my local)
Info of my system:
`[07/14/18]seed@VM:~/.../ff$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
[07/14/18]seed@VM:~/.../ff$ uname -a
Linux VM 4.8.0-36-generic #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:41 UTC 2017 i686 i686 i686 GNU/Linux
[07/14/18]seed@VM:~/.../ff$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`
I read in other places that this is a common error related with gcc and it was supposed to be patched for gcc versions > 5. I have the same OS and same gcc version on my local machine, in which it does compiles. Could it be the kernel version?
Thank you for your time.

**Comment by dgruss** [comment]
The code does not work on 32bit machines out of the box.
