### ISSUE TITLE
Regarding "self-compiled OpenSSL library" 

### ISSUE THREAD

**Issue by darshantank** [IAIK/flush_flush#4]
Respected Sir,

What do you mean by "**self-compiled OpenSSL library**" mentioned under "OpenSSL AES T-Table attack" section? and how do I create "**self-compiled OpenSSL library**"? 

How do I **enable it's T-Table-based AES implementation**?

kindly guide us in this regard. Thanking you

**Comment by dgruss** [comment]
> What do you mean by "*self-compiled OpenSSL library*" mentioned under
> "OpenSSL AES T-Table attack" section? and how do I create
> "*self-compiled OpenSSL library*"?

If you google for exactly that, you find the OpenSSLWiki as the first
result, providing a step-by-step explanation on how to do that.

> How do I *enable it's T-Table-based AES implementation*?

That's a change you have to do in the OpenSSL source code.

**Comment by JaspinderKaur07** [comment]
Sir is the change putting no-asm option during configuration of openssl.
