### ISSUE TITLE
T-table addresses are in increasing order

### ISSUE THREAD

**Issue by JaspinderKaur07** [IAIK/flush_flush#9]
When i calculated the T-table addresses they are in increasing order from Te0 to Te3.  The code you have given have it in reverse order. Execution is throwing segmentation fault even when in code addresses are set in decreasing order only.

**Comment by dgruss** [comment]
looks different on my system... should be trivial to fix in your code for your attack then...

**Comment by JaspinderKaur07** [comment]
I fixed that by setting te0 to te3 and so on. Still, it showed segmentation fault. is it working fine on your system?

**Comment by dgruss** [comment]
yes
